services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: fitness_tracker
    volumes:
      - db-data:/data/db
    networks:
      - mongo-compose-network
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend/.
    container_name: backend
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb

  mongodb-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
    ports:
      - "8888:8081"
    volumes:
      - db-data:/data/db

volumes:
  db-data:

networks:
    mongo-compose-network:
      driver: bridge
