services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: fitness_tracker
    volumes:
      - db-data:/data/db
    networks:
      - mongo-compose-network
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend/.
    container_name: backend
    env_file:
      - ./.env
    secrets:
      - firebase_token
    ports:
      - 80:8000
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb

secrets:
  firebase_token:
     file: ${DOCKER_FIREBASE_TOKEN_FILE}

volumes:
  db-data:

networks:
    mongo-compose-network:
      driver: bridge
